M48
; DRILL file {KiCad 8.0.5} date 2024-11-18T20:05:16+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-18T20:05:16+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X155.37Y-93.14
X155.37Y-115.14
X177.37Y-93.14
X177.37Y-115.14
T2
X176.53Y-68.58
M30
